server:
  port: 8071

spring:
  application:
    name: "configserver"
  profiles:
    #active: native # Used in case reading files from class path inside config server
    active: git # Used in case reading files from git repo
  cloud:
    config:
      server:
        #native:
        #  search-locations: "classpath:/config"
        git:
          uri: "https://github.com/MBA90/config-app.git"
          default-label: main
          timeout: 5
          force-pull: true
          clone-on-start: true
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
# this will enable encryption and decryption in cloud config server and provide implementation the api  /encrypt and /decrypt
encrypt:
  key: "Password@123"

# Enable actuator to get the actuator refresh path, so that i can read configuration properties in realtime
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true